# Generated by Django 4.1.7 on 2023-03-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0003_buyer_buyersubscription_book_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='age',
            field=models.IntegerField(default=20),
        ),
    ]
