# Generated by Django 4.2 on 2023-05-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0009_publisher_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
